apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.auth.adminPassword }}

---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.auth.password }}
