apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  rootPassword: {{ .Values.auth.rootPassword }}
  accessKey: {{ .Values.auth.accessKey }}
  secretKey: {{ .Values.auth.secretKey }}

{{- if .Values.keycloak.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}-keycloak-secret
  labels:
    {{- include "minio.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.keycloak.clientSecret }}
{{- end }}
