apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "minio.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "minio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "minio.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: minio
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - server
          {{- if eq .Values.mode "distributed" }}
          {{- range $i := until (int $.Values.replicaCount) }}
          - http://{{ include "minio.fullname" $ }}-{{ $i }}.{{ include "minio.fullname" $ }}-headless:9000/data
          {{- end }}
          {{- else }}
          - /data
          {{- end }}
          - --console-address
          - ":9001"
        env:
        - name: MINIO_ROOT_USER
          value: {{ .Values.auth.rootUser }}
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "minio.fullname" . }}-secret
              key: rootPassword
        {{- if .Values.keycloak.enabled }}
        - name: MINIO_IDENTITY_OPENID_CONFIG_URL
          value: {{ .Values.keycloak.url }}/realms/{{ .Values.keycloak.realm }}/.well-known/openid-configuration
        - name: MINIO_IDENTITY_OPENID_CLIENT_ID
          value: {{ .Values.keycloak.clientId }}
        - name: MINIO_IDENTITY_OPENID_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "minio.fullname" . }}-keycloak-secret
              key: clientSecret
        - name: MINIO_IDENTITY_OPENID_REDIRECT_URI
          value: {{ .Values.config.oidc.redirectUri }}
        - name: MINIO_IDENTITY_OPENID_CLAIM_NAME
          value: {{ .Values.config.oidc.claimName }}
        {{- end }}
        ports:
        - name: api
          containerPort: 9000
          protocol: TCP
        - name: console
          containerPort: 9001
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: api
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: api
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumeClaimTemplates:
      {{- if .Values.persistence.enabled }}
      - metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: {{ .Values.persistence.size }}
          {{- if .Values.persistence.storageClass }}
          storageClassName: {{ .Values.persistence.storageClass }}
          {{- end }}
      {{- end }}
